# [START jenkins_service_ui]
---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-ui
  namespace: jenkinsgcp
spec:
  type: NodePort
  selector:
    app: master
  ports:
    - protocol: TCP
      nodePort: 30000
      port: 8080
      targetPort: 8080
      name: ui
# [END jenkins_service_ui]
